// @ts-check
// Questo file gira in Node.js: niente codice lato browser o JSX qui dentro.

/**
 * La barra laterale è generata automaticamente dalla struttura della cartella
 * docs/. In pratica: crei un file .md, compare nel menu. L'ordine si controlla
 * con `sidebar_position` nel frontmatter dei file e con i `_category_.json`
 * delle cartelle.
 *
 * Se un giorno ti serve il controllo totale, sostituisci il blocco
 * `autogenerated` con l'elenco esplicito (esempio commentato in fondo).
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  documentazione: [{type: 'autogenerated', dirName: '.'}],

  // Esempio di barra laterale scritta a mano:
  // documentazione: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: 'Guida rapida',
  //     items: ['guida/installazione', 'guida/scrivere-una-pagina'],
  //   },
  // ],
};

export default sidebars;
